export type ISOStringDate = `${number}-${number}-${number}T${number}:${number}:${number}.${number}Z`;

export type ResourceAccommodation = {
    latitude: number,
    longitude: number,
    id: number,
    title: string,
    advertiser: string,
    description: string,
    isRenovated: boolean,
    phoneNumber: string,
    type: string,
    price: number,
    pricePerMeter: number,
    address: string,
    province: string,
    city: string,
    squareMeters: number,
    bedroomAmount: number,
    bathroomAmount: number,
    hasParking: boolean,
    isSecondHand: boolean,
    builtInWardrobes: boolean,
    builtYear: number | null,
    isFurnished: boolean,
    individualHeatingType: string,
    energyCertification: string | null,
    floor: number |null,
    hasExteriorView: boolean,
    hasInteriorView: boolean,
    hasElevator: boolean,
    date: ISOStringDate | null,
    street: string | null,
    neighborhood: string | null,
    district: string | null,
    hasTerrace: boolean,
    storageRoom: string,
    isKitchenEquipped: boolean,
    hasAirConditioning: boolean,
    hasPoolAccess: boolean,
    hasGarden: boolean,
    usefulSquareMeters: number | null,
    isAccessible: boolean,
    floors: number | null,
    isPetFriendly: boolean,
    hasBalcony: boolean,
}