-- CreateTable
CREATE TABLE `ResourceAccommodation` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `rowId` INTEGER NULL,
    `latitude` DOUBLE NOT NULL,
    `longitude` DOUBLE NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `advertiser` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NOT NULL,
    `isRenovated` BOOLEAN NOT NULL,
    `phoneNumber` VARCHAR(191) NOT NULL,
    `type` VARCHAR(191) NOT NULL,
    `price` DOUBLE NOT NULL,
    `pricePerMeter` DOUBLE NOT NULL,
    `address` VARCHAR(191) NOT NULL,
    `province` VARCHAR(191) NOT NULL,
    `city` VARCHAR(191) NOT NULL,
    `squareMeters` INTEGER NOT NULL,
    `bedroomAmount` INTEGER NOT NULL,
    `bathroomAmount` INTEGER NOT NULL,
    `hasParking` BOOLEAN NOT NULL,
    `isSecondHand` BOOLEAN NOT NULL,
    `builtInWardrobes` BOOLEAN NOT NULL,
    `builtYear` INTEGER NULL,
    `isFurnished` BOOLEAN NOT NULL,
    `individualHeatingType` VARCHAR(191) NOT NULL,
    `energyCertification` VARCHAR(191) NULL,
    `floor` INTEGER NULL,
    `hasExteriorView` BOOLEAN NOT NULL,
    `hasInteriorView` BOOLEAN NOT NULL,
    `hasElevator` BOOLEAN NOT NULL,
    `date` DATETIME(3) NULL,
    `street` VARCHAR(191) NULL,
    `neighborhood` VARCHAR(191) NULL,
    `district` VARCHAR(191) NULL,
    `hasTerrace` BOOLEAN NOT NULL,
    `storageRoom` VARCHAR(191) NOT NULL,
    `isKitchenEquipped` BOOLEAN NOT NULL,
    `hasAirConditioning` BOOLEAN NOT NULL,
    `hasPoolAccess` BOOLEAN NOT NULL,
    `hasGarden` BOOLEAN NOT NULL,
    `usefulSquareMeters` INTEGER NULL,
    `isAccessible` BOOLEAN NOT NULL,
    `floors` INTEGER NULL,
    `isPetFriendly` BOOLEAN NOT NULL,
    `hasBalcony` BOOLEAN NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
